// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ3fDXbp8AijHVH4RGFarOiZwltRVCzRQ',
    appId: '1:755342721880:android:10225bb575fa9b6feddb2d',
    messagingSenderId: '755342721880',
    projectId: 'shopsfirebase-a92b0',
    databaseURL: 'https://shopsfirebase-a92b0-default-rtdb.firebaseio.com',
    storageBucket: 'shopsfirebase-a92b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNBkGnRmj5Suot37mc5gTMdl39TFGpAW0',
    appId: '1:755342721880:ios:bb21a41123f6320deddb2d',
    messagingSenderId: '755342721880',
    projectId: 'shopsfirebase-a92b0',
    databaseURL: 'https://shopsfirebase-a92b0-default-rtdb.firebaseio.com',
    storageBucket: 'shopsfirebase-a92b0.firebasestorage.app',
    iosBundleId: 'com.example.mapme',
  );

}